GET http://localhost:8081/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWF0IjoxNjIzOTY1NDMwLCJleHAiOjE2MjM5NjYwMzB9.KfJLY6GqjK-0drUN0RjC_gX4_ljbKA_Ru3sE32JHzDs

###

DELETE http://localhost:8081/api/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWF0IjoxNjIzOTY1Mzk0fQ.NQhTnPsl_sWKcCVhKOPfwgP4DqYKpKA2g_PyodD_9Pg"
}

###

POST http://localhost:8081/api/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWF0IjoxNjIzOTY1Mzk0fQ.NQhTnPsl_sWKcCVhKOPfwgP4DqYKpKA2g_PyodD_9Pg"
}

###
POST http://localhost:8081/api/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "pwd": "test"
}

###
GET http://localhost:8080/api/v1/topChoice/get/test@hesge.ch/5

###
POST http://localhost:8080/api/v1/topChoice/post
Content-Type: application/json

{
    "userEmail": "test@hesge.ch",
    "href": "test2",
    "note": 2
}

###
PUT http://localhost:8080/api/v1/topChoice/put
Content-Type: application/json

{
    "userEmail": "test@hesge.ch",
    "href": "test2",
    "note": 5
}

###
DELETE http://localhost:8080/api/v1/topChoice/delete/
Content-Type: application/json

{
    "userEmail": "test@hesge.ch",
    "href": "test2"
}

 



